import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, unlinkSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';

const RESET = '\x1b[0m';
const DIM = '\x1b[2m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';

const CLAUDE_DIR = join(homedir(), '.claude');
const SETTINGS_FILE = join(CLAUDE_DIR, 'settings.json');
const SETTINGS_BACKUP = join(CLAUDE_DIR, 'settings.json.vbf-backup');

const VBF_DIR = join(homedir(), '.vibe-friends');
const WRAP_PREV = join(VBF_DIR, 'wrap-prev.sh');

function vbfStatuslineEntry() {
  // Absolute path to bin/vibe-friends.js (resolved from this file's location)
  const here = fileURLToPath(import.meta.url);
  const binPath = join(dirname(here), '..', 'bin', 'vibe-friends.js');
  return `${process.execPath} ${binPath} statusline-render`;
}

function tildePath(p) {
  const home = homedir();
  return p.startsWith(home) ? p.replace(home, '~') : p;
}

function readSettings() {
  if (!existsSync(SETTINGS_FILE)) return {};
  try {
    return JSON.parse(readFileSync(SETTINGS_FILE, 'utf-8'));
  } catch (err) {
    throw new Error(`Cannot parse ${SETTINGS_FILE}: ${err.message}`);
  }
}

function writeSettings(obj) {
  if (!existsSync(CLAUDE_DIR)) mkdirSync(CLAUDE_DIR, { recursive: true });
  writeFileSync(SETTINGS_FILE, JSON.stringify(obj, null, 2) + '\n', 'utf-8');
}

function ensureVbfDir() {
  if (!existsSync(VBF_DIR)) mkdirSync(VBF_DIR, { recursive: true });
}

function isOurEntry(cmd) {
  return typeof cmd === 'string' && cmd.includes('bin/vibe-friends.js') && cmd.includes('statusline-render');
}

export function runStatuslineInstall({ remove = false } = {}) {
  console.log();
  console.log('  Vibe Friends statusline — Claude Code footer 一行热帖');
  console.log();

  let settings;
  try {
    settings = readSettings();
  } catch (err) {
    console.error(`  ${YELLOW}[错误]${RESET} ${err.message}`);
    process.exit(1);
  }

  if (remove) {
    return uninstall(settings);
  }

  return install(settings);
}

function install(settings) {
  const ourEntry = vbfStatuslineEntry();
  const current = settings.statusLine?.command;

  if (isOurEntry(current)) {
    console.log(`  ${DIM}Vibe Friends statusline 已经装过了，无需重复。${RESET}`);
    console.log();
    return;
  }

  // Backup once (don't overwrite an existing backup, that'd lose history)
  if (existsSync(SETTINGS_FILE) && !existsSync(SETTINGS_BACKUP)) {
    copyFileSync(SETTINGS_FILE, SETTINGS_BACKUP);
    console.log(`  ${DIM}已备份原 settings.json → ${tildePath(SETTINGS_BACKUP)}${RESET}`);
  }

  ensureVbfDir();

  // If there's an existing statusLine.command, chain it
  if (current && typeof current === 'string' && current.trim().length > 0) {
    const wrapScript = `#!/bin/sh\n# Auto-generated by vibe-friends statusline install.\n# Original Claude Code statusLine.command — preserved here so vibe-friends\n# can append its own line beneath the existing statusline.\nexec ${current}\n`;
    writeFileSync(WRAP_PREV, wrapScript, 'utf-8');
    chmodSync(WRAP_PREV, 0o755);
    console.log(`  ${DIM}已链入原有 statusLine.command → ${tildePath(WRAP_PREV)}${RESET}`);
  } else {
    // Make sure no stale wrap script lingers
    try { unlinkSync(WRAP_PREV); } catch {}
  }

  settings.statusLine = {
    ...(settings.statusLine || {}),
    type: 'command',
    command: ourEntry,
  };
  writeSettings(settings);

  console.log();
  console.log(`  ${GREEN}[OK]${RESET} 已写入 statusLine.command`);
  console.log(`  ${DIM}下次 Claude Code 启动时即可在 footer 看到一行热帖。${RESET}`);
  console.log(`  ${DIM}卸载：npx @vibe-cafe/vibe-friends statusline --remove${RESET}`);
  console.log();
}

function uninstall(settings) {
  const current = settings.statusLine?.command;

  if (!isOurEntry(current)) {
    console.log(`  ${DIM}Vibe Friends statusline 没在 settings.json 里，无需卸载。${RESET}`);
    console.log();
    return;
  }

  // Restore from wrap-prev if present, otherwise just remove statusLine
  if (existsSync(WRAP_PREV)) {
    const wrapContent = readFileSync(WRAP_PREV, 'utf-8');
    const match = wrapContent.match(/^exec (.+)$/m);
    if (match) {
      settings.statusLine = {
        ...(settings.statusLine || {}),
        command: match[1].trim(),
      };
      console.log(`  ${DIM}已恢复原 statusLine.command${RESET}`);
    } else {
      delete settings.statusLine;
    }
    try { unlinkSync(WRAP_PREV); } catch {}
  } else {
    delete settings.statusLine;
  }

  writeSettings(settings);

  // Backup is left in place on purpose — user can manually consult / delete it
  console.log();
  console.log(`  ${GREEN}[OK]${RESET} Vibe Friends statusline 已卸载`);
  if (existsSync(SETTINGS_BACKUP)) {
    console.log(`  ${DIM}备份文件保留在 ${tildePath(SETTINGS_BACKUP)}，确认无问题后可删${RESET}`);
  }
  console.log();
}
